# Generated by Django 3.2.25 on 2024-09-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240915_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
